version: "3"
services:
  dummy:
    container_name: dummy
    build:
      context: ./dummy
      dockerfile: Dockerfile.dev
    image: gcr.io/nattapon/dummy
    volumes:
      - /app/node_modules
      - ./dummy:/app
    expose:
      - 3000
    ports:
      - 3000:3000
