apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/nattapon/nui_api
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-svc
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              value: postgres_password
            - name: PGPORT
              value: "5432"
