apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: gcr.io/nattapon/nui_worker
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: "6379"
